import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { Project } from '@/types/db';

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const client = await prisma.client.findFirst({
      where: {
        id,
        deletedAt: null,
      },
      include: {
        projects: {
          where: {
            deletedAt: null,
          },
          include: {
            payments: {
              select: {
                amount: true,
                paymentDate: true,
              },
            },
            materialPurchases: {
              select: {
                amount: true,
              },
            },
            labourCosts: {
              select: {
                amount: true,
              },
            },
          },
          orderBy: {
            createdAt: 'desc',
          },
        },
      },
    });

    if (!client) {
      return NextResponse.json({ error: 'Client not found' }, { status: 404 });
    }

    const projectsWithPayments = client.projects as any[];
    // Calculate total business value generated by client (sum of quoted amount of all active/completed projects)
    const totalBusinessValue = projectsWithPayments.reduce((sum: number, p: any) => sum + Number(p.quotedAmount), 0);

    // Calculate detailed financial summary
    const totalAmountReceived = projectsWithPayments.reduce(
      (sum: number, p: any) => sum + p.payments.reduce((s: number, pay: any) => s + Number(pay.amount), 0),
      0
    );
    const outstandingAmount = projectsWithPayments.reduce((sum: number, p: any) => {
      if (p.status === 'Cancelled') return sum;
      const pReceived = p.payments.reduce((s: number, pay: any) => s + Number(pay.amount), 0);
      return sum + Math.max(0, Number(p.quotedAmount) - pReceived);
    }, 0);
    const totalMaterialCost = projectsWithPayments.reduce(
      (sum: number, p: any) => sum + p.materialPurchases.reduce((s: number, mat: any) => s + Number(mat.amount), 0),
      0
    );
    const totalLabourCost = projectsWithPayments.reduce(
      (sum: number, p: any) => sum + p.labourCosts.reduce((s: number, lab: any) => s + Number(lab.amount), 0),
      0
    );
    const profit = totalBusinessValue - totalMaterialCost - totalLabourCost; // Profit = Quoted - Material - Labour
    const numberOfProjects = projectsWithPayments.length;

    let lastPaymentDate: Date | null = null;
    for (const p of projectsWithPayments) {
      for (const pay of p.payments) {
        const payDate = new Date(pay.paymentDate);
        if (!lastPaymentDate || payDate > lastPaymentDate) {
          lastPaymentDate = payDate;
        }
      }
    }

    return NextResponse.json({
      ...client,
      totalBusinessValue,
      financialSummary: {
        totalProjectValue: totalBusinessValue,
        totalAmountReceived,
        outstandingAmount,
        totalMaterialCost,
        totalLabourCost,
        profit,
        numberOfProjects,
        lastPaymentDate: lastPaymentDate ? lastPaymentDate.toISOString() : null,
      },
    }, {
      headers: {
        'Cache-Control': 'no-store, max-age=0',
      },
    });
  } catch (error) {
    console.error('Error fetching client details:', error);
    return NextResponse.json({ error: 'Failed to fetch client details' }, { status: 500 });
  }
}

export async function PUT(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const body = await req.json();
    const { name, phone, alternatePhone, location, address, referredBy, remarks } = body;

    if (!name || !phone) {
      return NextResponse.json({ error: 'Name and Phone are required' }, { status: 400 });
    }

    // Phone validations: Exactly 10 digits, only digits allowed.
    const phoneRegex = /^\d{10}$/;
    if (!phoneRegex.test(phone.trim())) {
      return NextResponse.json({ error: 'Please enter a valid 10-digit mobile number.' }, { status: 400 });
    }
    if (alternatePhone && alternatePhone.trim() && !phoneRegex.test(alternatePhone.trim())) {
      return NextResponse.json({ error: 'Please enter a valid 10-digit mobile number.' }, { status: 400 });
    }

    const updatedClient = await prisma.client.update({
      where: { id },
      data: {
        name: name.trim(),
        phone: phone.trim(),
        alternatePhone: alternatePhone ? alternatePhone.trim() : null,
        location: location ? location.trim() : null,
        address: address ? address.trim() : null,
        referredBy: referredBy ? referredBy.trim() : null,
        remarks: remarks ? remarks.trim() : null,
      },
    });

    return NextResponse.json(updatedClient);
  } catch (error) {
    console.error('Error updating client:', error);
    return NextResponse.json({ error: 'Failed to update client' }, { status: 500 });
  }
}

export async function DELETE(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    // Perform soft delete
    const softDeletedClient = await prisma.client.update({
      where: { id },
      data: {
        deletedAt: new Date(),
      },
    });

    // Also soft-delete all projects under this client for integrity
    await prisma.project.updateMany({
      where: {
        clientId: id,
        deletedAt: null,
      },
      data: {
        deletedAt: new Date(),
      },
    });

    return NextResponse.json({ message: 'Client soft-deleted successfully' });
  } catch (error) {
    console.error('Error deleting client:', error);
    return NextResponse.json({ error: 'Failed to delete client' }, { status: 500 });
  }
}
