import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { Project } from '@/types/db';

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const client = await prisma.client.findFirst({
      where: {
        id,
        deletedAt: null,
      },
      include: {
        projects: {
          where: {
            deletedAt: null,
          },
          orderBy: {
            createdAt: 'desc',
          },
        },
      },
    });

    if (!client) {
      return NextResponse.json({ error: 'Client not found' }, { status: 404 });
    }

    // Calculate total business value generated by client (sum of quoted amount of all active/completed projects)
    const totalBusinessValue = client.projects.reduce((sum: number, p: Project) => sum + Number(p.quotedAmount), 0);

    return NextResponse.json({
      ...client,
      totalBusinessValue,
    });
  } catch (error) {
    console.error('Error fetching client details:', error);
    return NextResponse.json({ error: 'Failed to fetch client details' }, { status: 500 });
  }
}

export async function PUT(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const body = await req.json();
    const { name, phone, alternatePhone, location, address, referredBy, remarks } = body;

    if (!name || !phone) {
      return NextResponse.json({ error: 'Name and Phone are required' }, { status: 400 });
    }

    const updatedClient = await prisma.client.update({
      where: { id },
      data: {
        name,
        phone,
        alternatePhone: alternatePhone || null,
        location: location || null,
        address: address || null,
        referredBy: referredBy || null,
        remarks: remarks || null,
      },
    });

    return NextResponse.json(updatedClient);
  } catch (error) {
    console.error('Error updating client:', error);
    return NextResponse.json({ error: 'Failed to update client' }, { status: 500 });
  }
}

export async function DELETE(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    // Perform soft delete
    const softDeletedClient = await prisma.client.update({
      where: { id },
      data: {
        deletedAt: new Date(),
      },
    });

    // Also soft-delete all projects under this client for integrity
    await prisma.project.updateMany({
      where: {
        clientId: id,
        deletedAt: null,
      },
      data: {
        deletedAt: new Date(),
      },
    });

    return NextResponse.json({ message: 'Client soft-deleted successfully' });
  } catch (error) {
    console.error('Error deleting client:', error);
    return NextResponse.json({ error: 'Failed to delete client' }, { status: 500 });
  }
}
